### PR TITLE
OSX Mem.cpp fix

### PR DESCRIPTION
**Pull request by djfinch**

### CODE REVIEW

**Comment by Bendr0id** [comment]
Thx. I'll test if this also works for Windows and Linux build, then i'll integrate.. Otherwise i need to add some ifdefs. Would appreciate if you can test once i'm done. I don't have a test OSX machine.

**Comment by Bendr0id** [comment]
Linux works.

**Comment by djfinch** [comment]
Regarding Win build...
 VS 2017 Community, CMake 3.10.2, pre-compiled deps from your repo, forced to use all options (`cmake -G "Visual Studio 15 2017 Win64" -T v141,host=x64 .. -DWITH_LIBCPUID=ON -DWITH_AEON=ON -DWITH_HTTPD=ON -DWITH_CC_CLIENT=ON -DWITH_CC_SERVER=ON -DWITH_TLS=ON`)

image

**Comment by Bendr0id** [comment]
Awesome.

**Comment by Bendr0id** [comment]
Btw. when you disable all options tls/server/http you dont have any depencies. I just tried it.

**Pull request merged**
