### PR TITLE
Asm optimizations

### PR DESCRIPTION
**Pull request by Bendr0id**

### CODE REVIEW

**Comment by Bendr0id** [comment]
On intel cpus there is a nice benefit 10-15%. But i need to fix 32bit windows anyways. that should fix it for apple too.. Maybe we can add an ifdef here for alignas.. Can you do that..?

**Comment by djfinch** [comment]
Thanks! I see it now. It literally adds around 10%... Here is PR https://github.com/Bendr0id/xmrigCC/pull/184. OSX and UBUNTU (Kde Neon Latest) is OK so far. I don't have any Windows machine to test with...

**Comment by Bendr0id** [comment]
awesome, i was going to push the same changes, but you've been faster. Thx. appreciate!

**Comment by djfinch** [comment]
you're welcome. maybe I have more spare time :) btw: your awesome work, it's really ~10% faster. cn/2 works as well...
image

**Pull request merged**
